import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
key.c
led.c
at_socket_a9g.c
minmea.c
""")


group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
